import Foundation

/// Drives Codex through `codex app-server`: JSON-RPC over stdio, one
/// message per line, without the `"jsonrpc": "2.0"` field.
///
/// We call `initialize`, `thread/start` / `thread/resume`, `turn/start`,
/// `turn/steer` and `turn/interrupt`. Codex sends notifications (turn and
/// item lifecycle, deltas) and server requests (approvals, questions),
/// which we answer with responses carrying the same id.
///
/// Wire types are generated by `codex app-server generate-ts`; the fields
/// used here were checked against codex-cli 0.156.
actor CodexProvider: AgentProvider {
    nonisolated let kind: AgentProviderKind = .codex
    nonisolated let capabilities = AgentCapabilities(
        liveModelSwitch: true,
        steering: true,
        conversationRevert: true
    )
    nonisolated let events: AsyncStream<AgentEvent>
    private let continuation: AsyncStream<AgentEvent>.Continuation

    /// Oldest codex-cli release the protocol handling was checked against.
    static let minimumTestedVersion = "0.150.0"

    private var config: AgentSessionConfig?
    private var process: JSONLineProcess?
    private var mapper = CodexEventMapper()
    private var threadId: String?
    private var model: String?
    private var effort: String?
    private var defaultModel: String?

    private var nextRequestId: Int64 = 1
    private var pending = PendingReplies<Int64>()
    /// Server requests awaiting the user, by request key.
    private var serverRequests: [String: ServerRequest] = [:]

    private var activeTurnId: String?
    /// Subagent threads spawned by ours, with their running turn if any.
    private var childThreads: [String: String?] = [:]
    /// A turn/start is in flight; its turn id isn't known yet.
    private var startingTurn = false
    /// Stop was pressed while `startingTurn`: interrupt once the id is known.
    private var interruptWhenStarted = false
    private var runtimeMode: AgentRuntimeMode = .supervised
    private var interactionMode: AgentInteractionMode = .normal
    private var stopping = false

    private struct ServerRequest {
        var id: JSONValue
        var method: String
        var params: JSONValue
    }

    init() {
        (events, continuation) = AsyncStream.makeStream(of: AgentEvent.self, bufferingPolicy: .unbounded)
    }

    /// Request ids are JSON numbers or strings; normalise to a string key.
    static func requestKey(_ id: JSONValue) -> String {
        switch id {
        case let .int(i): return "codex-\(i)"
        case let .string(s): return "codex-\(s)"
        default: return "codex-\(id.serializedString())"
        }
    }

    // MARK: - Lifecycle

    func start(_ config: AgentSessionConfig) async throws {
        self.config = config
        runtimeMode = config.runtimeMode
        interactionMode = config.interactionMode
        model = config.model
        effort = config.effort

        _ = await LoginShellPath.get()
        let env = Subprocess.inheritedEnvironment(overrides: ["JETLINE": "1"])
        let process = JSONLineProcess(.init(
            executable: config.executable, args: ["app-server"] + (config.tools?.args(for: .codex) ?? []), cwd: config.cwd, env: env
        ))
        try process.start()
        self.process = process
        startReading(process)

        let version: String?
        do {
            let result = try await request("initialize", [
                "clientInfo": ["name": "jetline", "title": "Jetline", "version": .string(Self.appVersion)],
                "capabilities": ["experimentalApi": true]
            ], timeout: .seconds(30))
            version = Self.cliVersion(fromUserAgent: result["userAgent"]?.string)
            try await notify("initialized", nil)
        } catch {
            self.process = nil
            await process.terminate(grace: .milliseconds(200))
            throw AgentError.launchFailed(process.stderrTail.nonBlank ?? error.localizedDescription)
        }

        if let version, Self.compare(version, Self.minimumTestedVersion) == .orderedAscending {
            emitNotice(.warning, "codex \(version) is older than Jetline has been tested with (\(Self.minimumTestedVersion)). Update Codex if the chat misbehaves.")
        }

        let thread: (id: String, model: String?)
        do {
            thread = try await openThread(resume: config.resume)
        } catch {
            self.process = nil
            await process.terminate(grace: .milliseconds(200))
            throw error
        }
        threadId = thread.id
        if let resolved = thread.model { model = resolved }

        let models = (try? await listModels()) ?? []
        defaultModel = models.first(where: \.isDefault)?.id ?? models.first?.id
        continuation.yield(.ready(AgentSessionInfo(
            resume: AgentResumeCursor(sessionId: thread.id),
            model: model,
            models: models,
            commands: [],
            cliVersion: version
        )))
        if let model { continuation.yield(.modelChanged(model)) }
        // Updates only arrive as turns spend usage; read where it stands now.
        Task { [weak self] in
            guard let self, let result = try? await self.request("account/rateLimits/read", .null, timeout: .seconds(15)) else { return }
            let windows = CodexEventMapper.rateLimits(result["rateLimits"])
            if !windows.isEmpty { self.continuation.yield(.rateLimits(windows)) }
        }
    }

    private func openThread(resume: AgentResumeCursor?) async throws -> (id: String, model: String?) {
        guard let config else { throw AgentError.notRunning }
        let policy = Self.policy(for: runtimeMode)
        var params: [String: JSONValue] = [
            "cwd": .string(config.cwd),
            "approvalPolicy": policy.approval,
            "sandbox": .string(policy.sandboxMode),
            // Always explicit: a resumed thread otherwise keeps whatever
            // reviewer it last ran with.
            "approvalsReviewer": .string(policy.reviewer)
        ]
        if let model { params["model"] = .string(model) }

        if let resume {
            var resumeParams = params
            resumeParams["threadId"] = .string(resume.sessionId)
            resumeParams["excludeTurns"] = true
            do {
                let result = try await request("thread/resume", .object(resumeParams))
                if let id = result["thread"]?["id"]?.string {
                    return (id, result["model"]?.string)
                }
            } catch let error as AgentError where Self.isMissingThread(error) {
                // Only a thread that's really gone justifies starting over;
                // anything else (a timeout) would silently lose the context.
                emitNotice(.warning, "The previous Codex thread no longer exists, so a new one was started.")
            }
        }
        let result = try await request("thread/start", .object(params))
        guard let id = result["thread"]?["id"]?.string else {
            throw AgentError.protocolError("thread/start returned no thread id")
        }
        return (id, result["model"]?.string)
    }

    static func isMissingThread(_ error: AgentError) -> Bool {
        guard case let .requestFailed(message) = error else { return false }
        let lower = message.lowercased()
        return lower.contains("not found") || lower.contains("no rollout") || lower.contains("does not exist")
    }

    private func listModels() async throws -> [AgentModelOption] {
        var models: [JSONValue] = []
        var cursor: JSONValue = .null
        for _ in 0..<10 {
            let result = try await request("model/list", ["cursor": cursor], timeout: .seconds(15))
            models += result["data"]?.array ?? []
            guard let next = result["nextCursor"]?.string, !next.isEmpty else { break }
            cursor = .string(next)
        }
        return models.compactMap { model in
            guard model["hidden"]?.bool != true, let id = model["id"]?.string else { return nil }
            return AgentModelOption(
                id: id,
                displayName: model["displayName"]?.string ?? id,
                description: model["description"]?.string,
                efforts: model["supportedReasoningEfforts"]?.array?.compactMap { $0["reasoningEffort"]?.string } ?? [],
                defaultEffort: model["defaultReasoningEffort"]?.string,
                isDefault: model["isDefault"]?.bool ?? false
            )
        }
    }

    func stop() async {
        stopping = true
        if let process {
            await process.terminate()
        }
    }

    // MARK: - Reading

    private func startReading(_ process: JSONLineProcess) {
        Task { [weak self] in
            for await line in process.lines {
                await self?.handle(line: line)
            }
            let status = await process.waitForExit()
            await self?.processEnded(process, status: status)
        }
    }

    private func handle(line: Data) {
        guard let message = try? JSONValue.parse(line) else { return }
        let method = message["method"]?.string
        let id = message["id"]
        switch (method, id) {
        case let (nil, id?):
            // Response to one of our requests.
            guard let key = id.int.map(Int64.init) else { return }
            if let error = message["error"] {
                pending.resolve(key, with: .failure(AgentError.requestFailed(error["message"]?.string ?? "Codex request failed")))
            } else {
                pending.resolve(key, with: .success(message["result"] ?? .null))
            }
        case let (method?, id?):
            handleServerRequest(id: id, method: method, params: message["params"] ?? .null)
        case let (method?, nil):
            handleNotification(method: method, params: message["params"] ?? .null)
        default:
            break
        }
    }

    private func handleNotification(method: String, params: JSONValue) {
        // Codex can host several threads per process: ours, and subagent
        // threads it spawned. Subagent threads only matter for their live
        // turns (interrupt stops them first) and their resolved requests.
        if let thread = params["threadId"]?.string, let threadId, thread != threadId {
            trackChildThread(thread, method: method, params: params)
            return
        }
        // A usage-limit error is repeated by the failed turn/completed.
        if method == "error", params["error"]?["codexErrorInfo"]?.string == "usageLimitExceeded" { return }
        let events = mapper.map(method: method, params: params)
        for case let .item(item) in events {
            if case .subagent = item.content, let raw = params["item"] {
                for child in raw["receiverThreadIds"]?.array?.compactMap(\.string) ?? []
                where childThreads[child] == nil {
                    childThreads[child] = .some(nil)
                }
            }
        }
        for event in events {
            switch event {
            case let .turnStarted(id):
                // Already announced from the turn/start response.
                if activeTurnId == id { continue }
                activeTurnId = id
                startingTurn = false
                interruptIfRequested()
            case let .requestClosed(id):
                serverRequests.removeValue(forKey: id)
            default:
                break
            }
            continuation.yield(event)
            if case let .turnCompleted(id, outcome) = event, id == activeTurnId {
                activeTurnId = nil
                closeAllRequests()
                if interactionMode == .plan, outcome == .completed,
                   let plan = mapper.completedPlans.values.first(where: { !$0.isEmpty }) {
                    continuation.yield(.requestOpened(AgentRequest(
                        id: "plan-\(id)", turnId: id, itemId: nil, kind: .plan(text: plan)
                    )))
                }
            }
        }
    }

    private func trackChildThread(_ thread: String, method: String, params: JSONValue) {
        guard childThreads.keys.contains(thread) else { return }
        switch method {
        case "turn/started":
            childThreads[thread] = params["turn"]?["id"]?.string
        case "turn/completed":
            childThreads[thread] = .some(nil)
        case "serverRequest/resolved":
            if let id = params["requestId"] {
                let key = Self.requestKey(id)
                if serverRequests.removeValue(forKey: key) != nil {
                    continuation.yield(.requestClosed(id: key))
                }
            }
        default:
            break
        }
    }

    private func processEnded(_ ended: JSONLineProcess, status: Int32) {
        guard ended === process else { return }
        process = nil
        pending.failAll(AgentError.notRunning)
        closeAllRequests()
        continuation.yield(.exited(AgentExit(status: status, stderr: ended.stderrTail, expected: stopping)))
        continuation.finish()
    }

    // MARK: - JSON-RPC

    private func request(_ method: String, _ params: JSONValue, timeout: Duration = .seconds(60)) async throws -> JSONValue {
        guard let process else { throw AgentError.notRunning }
        let id = nextRequestId
        nextRequestId += 1
        let message: JSONValue = ["id": .int(id), "method": .string(method), "params": params]
        let timeoutTask = Task { [weak self] in
            try? await Task.sleep(for: timeout)
            await self?.failRequest(id, AgentError.requestFailed("Codex didn't answer `\(method)`."))
        }
        defer { timeoutTask.cancel() }
        return try await withCheckedThrowingContinuation { cont in
            pending.add(id, cont)
            Task {
                do {
                    try await process.send(message)
                } catch {
                    self.failRequest(id, error)
                }
            }
        }
    }

    private func failRequest(_ id: Int64, _ error: Error) {
        pending.resolve(id, with: .failure(error))
    }

    private func notify(_ method: String, _ params: JSONValue?) async throws {
        guard let process else { throw AgentError.notRunning }
        var message: [String: JSONValue] = ["method": .string(method)]
        if let params { message["params"] = params }
        try await process.send(.object(message))
    }

    private func respond(id: JSONValue, result: JSONValue) {
        guard let process else { return }
        Task { try? await process.send(["id": id, "result": result]) }
    }

    private func respondError(id: JSONValue, code: Int64, message: String) {
        guard let process else { return }
        Task { try? await process.send(["id": id, "error": ["code": .int(code), "message": .string(message)]]) }
    }

    // MARK: - Server requests

    private func handleServerRequest(id: JSONValue, method: String, params: JSONValue) {
        let key = Self.requestKey(id)
        let kind: AgentRequest.Kind
        switch method {
        case "item/commandExecution/requestApproval":
            let command = params["command"]?.string.map(CodexEventMapper.unwrapShell)
            let isNetwork = params["networkApprovalContext"].map { !$0.isNull } ?? false
            kind = .approval(AgentApproval(
                category: isNetwork ? .network : .command,
                title: isNetwork ? "Allow network access?" : "Run this command?",
                detail: command,
                reason: params["reason"]?.string,
                allowsSessionScope: true
            ))
        case "item/fileChange/requestApproval":
            var paths: [String] = []
            if let itemId = params["itemId"]?.string,
               case let .fileChange(change)? = mapper.items[itemId]?.content {
                paths = change.edits.map(\.path)
            }
            let root = config?.cwd ?? ""
            kind = .approval(AgentApproval(
                category: .fileChange,
                title: paths.count == 1 ? "Apply this change?" : "Apply these changes?",
                detail: paths.map { $0.relative(to: root) }
                    .joined(separator: "\n").nonBlank ?? params["grantRoot"]?.string,
                reason: params["reason"]?.string,
                allowsSessionScope: true
            ))
        case "item/permissions/requestApproval":
            kind = .approval(AgentApproval(
                category: .permissions,
                title: "Grant additional permissions?",
                detail: params["permissions"]?.prettyPrinted(),
                reason: params["reason"]?.string,
                allowsSessionScope: true
            ))
        case "item/tool/requestUserInput":
            let questions = (params["questions"]?.array ?? []).map { q in
                AgentQuestion(
                    id: q["id"]?.string ?? UUID().uuidString,
                    header: q["header"]?.string,
                    prompt: q["question"]?.string ?? "",
                    options: (q["options"]?.array ?? []).map {
                        .init(label: $0["label"]?.string ?? "", description: $0["description"]?.string?.nonBlank)
                    },
                    allowsMultiple: false,
                    allowsFreeform: q["isOther"]?.bool ?? (q["options"]?.array?.isEmpty ?? true)
                )
            }
            guard !questions.isEmpty else {
                respond(id: id, result: ["answers": [:]])
                return
            }
            kind = .questions(questions)
        case "mcpServer/elicitation/request":
            // Codex asks for MCP and connector tool approval through form
            // elicitations. URL-mode ones (OAuth pages) have no UI here.
            guard params["mode"]?.string != "url" else {
                respond(id: id, result: ["action": "decline", "content": nil, "_meta": nil])
                return
            }
            let elicitation = CodexElicitation(params: params)
            kind = .approval(AgentApproval(
                category: .tool,
                title: "Allow \(elicitation.appName)?",
                detail: params["message"]?.string,
                reason: nil,
                allowsSessionScope: elicitation.offersSessionScope
            ))
        default:
            respondError(id: id, code: -32601, message: "Jetline doesn't support \(method)")
            return
        }
        serverRequests[key] = ServerRequest(id: id, method: method, params: params)
        continuation.yield(.requestOpened(AgentRequest(
            id: key,
            turnId: params["turnId"]?.string ?? activeTurnId,
            itemId: params["itemId"]?.string,
            kind: kind
        )))
    }

    func respond(to requestId: String, with decision: AgentApprovalDecision) async {
        guard let request = serverRequests.removeValue(forKey: requestId) else { return }
        if request.method == "mcpServer/elicitation/request" {
            respond(id: request.id, result: CodexElicitation(params: request.params).response(for: decision))
        } else if request.method == "item/permissions/requestApproval" {
            switch decision {
            case .allowOnce, .allowForSession:
                respond(id: request.id, result: [
                    "permissions": Self.granted(from: request.params["permissions"]),
                    "scope": decision == .allowForSession ? "session" : "turn"
                ])
            case .deny, .cancel:
                respond(id: request.id, result: ["permissions": [:], "scope": "turn"])
            }
        } else {
            let value: String
            switch decision {
            case .allowOnce: value = "accept"
            case .allowForSession: value = "acceptForSession"
            case .deny: value = "decline"
            case .cancel: value = "cancel"
            }
            respond(id: request.id, result: ["decision": .string(value)])
        }
        continuation.yield(.requestClosed(id: requestId))
    }

    /// Grant exactly what was requested (dropping nulls, which the response
    /// schema doesn't allow).
    private static func granted(from requested: JSONValue?) -> JSONValue {
        guard let object = requested?.object else { return [:] }
        return .object(object.filter { !$0.value.isNull })
    }

    func answer(_ requestId: String, answers: [String: [String]]) async {
        guard let request = serverRequests.removeValue(forKey: requestId) else { return }
        let payload = answers.mapValues { values -> JSONValue in
            ["answers": .array(values.map(JSONValue.string))]
        }
        respond(id: request.id, result: ["answers": .object(payload)])
        continuation.yield(.requestClosed(id: requestId))
    }

    func resolvePlan(_ requestId: String, with decision: AgentPlanDecision) async -> AgentTurnInput? {
        continuation.yield(.requestClosed(id: requestId))
        switch decision {
        case let .implement(mode):
            runtimeMode = mode
            continuation.yield(.runtimeModeChanged(mode))
            continuation.yield(.interactionModeChanged(.normal))
            return AgentTurnInput(text: "Implement the plan.", interactionMode: .normal)
        case let .keepPlanning(feedback):
            return feedback?.nonBlank.map { AgentTurnInput(text: $0, interactionMode: .plan) }
        }
    }

    /// Settle every open request with the response shape its method
    /// expects, so nothing is left blocking the turn.
    private func closeAllRequests() {
        for (key, request) in serverRequests {
            respond(id: request.id, result: Self.cancelResponse(for: request))
            continuation.yield(.requestClosed(id: key))
        }
        serverRequests.removeAll()
    }

    private static func cancelResponse(for request: ServerRequest) -> JSONValue {
        switch request.method {
        case "item/tool/requestUserInput": return ["answers": [:]]
        case "item/permissions/requestApproval": return ["permissions": [:], "scope": "turn"]
        case "mcpServer/elicitation/request": return ["action": "cancel", "content": nil, "_meta": nil]
        default: return ["decision": "cancel"]
        }
    }

    // MARK: - Turns

    func send(_ input: AgentTurnInput) async throws {
        guard let threadId else { throw AgentError.notRunning }
        if let model = input.model { self.model = model }
        if let effort = input.effort { self.effort = effort }
        let clientId = "user-\(UUID().uuidString.lowercased())"
        let userInput: [JSONValue] = [["type": "text", "text": .string(input.text), "text_elements": []]]
            + input.images.map { ["type": "localImage", "path": .string($0.path)] }

        // Steer the running turn when there is one.
        if let turnId = activeTurnId {
            continuation.yield(.item(AgentItem(
                id: clientId, turnId: turnId, status: .completed,
                content: .userMessage(.init(text: input.text, images: input.images.map(\.path)))
            )))
            _ = try await request("turn/steer", [
                "threadId": .string(threadId),
                "input": .array(userInput),
                "expectedTurnId": .string(turnId),
                "clientUserMessageId": .string(clientId)
            ])
            return
        }

        interactionMode = input.interactionMode
        let policy = Self.policy(for: runtimeMode)
        var params: [String: JSONValue] = [
            "threadId": .string(threadId),
            "input": .array(userInput),
            "clientUserMessageId": .string(clientId),
            "approvalPolicy": policy.approval,
            "sandboxPolicy": policy.sandboxPolicy,
            "approvalsReviewer": .string(policy.reviewer)
        ]
        if let model { params["model"] = .string(model) }
        if let effort { params["effort"] = .string(effort) }
        // Always sent, so leaving plan mode takes effect; `settings.model`
        // is required, hence the fallback.
        if let collaborationModel = model ?? defaultModel {
            params["collaborationMode"] = [
                "mode": .string(interactionMode == .plan ? "plan" : "default"),
                "settings": [
                    "model": .string(collaborationModel),
                    "reasoning_effort": .optional(effort),
                    "developer_instructions": nil
                ]
            ]
        }

        startingTurn = true
        let result: JSONValue
        do {
            result = try await request("turn/start", .object(params))
        } catch {
            startingTurn = false
            interruptWhenStarted = false
            throw error
        }
        // `turn/started` usually lands first, but the response carries the
        // id too; use whichever arrives.
        if let turnId = result["turn"]?["id"]?.string, activeTurnId == nil, startingTurn {
            activeTurnId = turnId
            startingTurn = false
            continuation.yield(.turnStarted(id: turnId))
            interruptIfRequested()
        }
        continuation.yield(.item(AgentItem(
            id: clientId, turnId: activeTurnId, status: .completed,
            content: .userMessage(.init(text: input.text, images: input.images.map(\.path)))
        )))
    }

    func interrupt() async {
        guard let threadId else { return }
        guard let turnId = activeTurnId else {
            if startingTurn { interruptWhenStarted = true }
            return
        }
        interruptWhenStarted = false
        // Cancel open approvals first so the turn isn't left waiting on
        // them while it winds down.
        closeAllRequests()
        // Stop live subagent turns before the parent, each bounded: an
        // unresponsive child mustn't block the stop.
        for (child, childTurn) in childThreads {
            guard let childTurn else { continue }
            _ = try? await request("turn/interrupt", [
                "threadId": .string(child), "turnId": .string(childTurn)
            ], timeout: .seconds(3))
        }
        _ = try? await request("turn/interrupt", [
            "threadId": .string(threadId), "turnId": .string(turnId)
        ], timeout: .seconds(10))
    }

    private func interruptIfRequested() {
        guard interruptWhenStarted else { return }
        interruptWhenStarted = false
        Task { await self.interrupt() }
    }

    // MARK: - Revert

    /// Paginated threads (current Codex) truncate at a turn boundary with
    /// `thread/revert`; older, non-paginated ones only support the
    /// count-based `thread/rollback`. Same split as T3 Code.
    func revert(toBefore turnId: String) async throws {
        guard let threadId else { throw AgentError.notRunning }
        let metadata = try? await request("thread/read", ["threadId": .string(threadId), "includeTurns": false])
        let mode = metadata?["thread"]?["historyMode"]?.string
        if mode == nil || mode == "paginated" {
            _ = try await request("thread/revert", ["threadId": .string(threadId), "beforeTurnId": .string(turnId)])
            return
        }
        let history = try await request("thread/read", ["threadId": .string(threadId), "includeTurns": true])
        let turnIds = history["thread"]?["turns"]?.array?.compactMap { $0["id"]?.string } ?? []
        guard let index = turnIds.firstIndex(of: turnId) else {
            throw AgentError.unsupported("Codex no longer has this turn in its history.")
        }
        _ = try await request("thread/rollback", ["threadId": .string(threadId), "numTurns": .int(Int64(turnIds.count - index))])
    }

    // MARK: - Settings

    func setRuntimeMode(_ mode: AgentRuntimeMode) async throws {
        // Applied with the next turn/start, which takes the policy as
        // "this turn and subsequent turns".
        runtimeMode = mode
    }

    func setModel(_ model: String?) async throws {
        self.model = model
        if let model { continuation.yield(.modelChanged(model)) }
    }

    func setRemoteControl(_ enabled: Bool, name: String?) async throws -> URL? {
        throw AgentError.unsupported("Remote Control")
    }

    // MARK: - Mapping helpers

    struct Policy {
        var approval: JSONValue
        var sandboxMode: String
        var sandboxPolicy: JSONValue
        var reviewer: String
    }

    static func policy(for mode: AgentRuntimeMode) -> Policy {
        let workspaceWrite: JSONValue = [
            "type": "workspaceWrite",
            "writableRoots": [],
            "networkAccess": false,
            "excludeTmpdirEnvVar": false,
            "excludeSlashTmp": false
        ]
        switch mode {
        case .supervised:
            // `untrusted` asks before anything that isn't a known-safe
            // read. The sandbox is workspace-write rather than read-only:
            // an approved command runs inside it, and under read-only the
            // user would approve a write only to watch it fail with EPERM.
            return Policy(approval: "untrusted", sandboxMode: "workspace-write", sandboxPolicy: workspaceWrite, reviewer: "user")
        case .acceptEdits:
            return Policy(approval: "on-request", sandboxMode: "workspace-write", sandboxPolicy: workspaceWrite, reviewer: "user")
        case .auto:
            return Policy(approval: "on-request", sandboxMode: "workspace-write", sandboxPolicy: workspaceWrite, reviewer: "auto_review")
        case .fullAccess:
            return Policy(
                approval: "never", sandboxMode: "danger-full-access",
                sandboxPolicy: ["type": "dangerFullAccess"], reviewer: "user"
            )
        }
    }

    /// `initialize` reports `<client>/<codex version> (<os>) ...`.
    static func cliVersion(fromUserAgent agent: String?) -> String? {
        guard let agent,
              let slash = agent.firstIndex(of: "/") else { return nil }
        let rest = agent[agent.index(after: slash)...]
        let version = rest.prefix { !$0.isWhitespace }
        return version.isEmpty ? nil : String(version)
    }

    static func compare(_ a: String, _ b: String) -> ComparisonResult {
        let lhs = a.split(separator: ".").map { Int($0.prefix { $0.isNumber }) ?? 0 }
        let rhs = b.split(separator: ".").map { Int($0.prefix { $0.isNumber }) ?? 0 }
        for i in 0..<max(lhs.count, rhs.count) {
            let l = i < lhs.count ? lhs[i] : 0
            let r = i < rhs.count ? rhs[i] : 0
            if l != r { return l < r ? .orderedAscending : .orderedDescending }
        }
        return .orderedSame
    }

    private static var appVersion: String {
        Bundle.main.object(forInfoDictionaryKey: "CFBundleShortVersionString") as? String ?? "dev"
    }

    private func emitNotice(_ level: AgentItem.Notice.Level, _ text: String) {
        continuation.yield(.item(.notice(level, text, turnId: activeTurnId)))
    }
}
