#!/usr/bin/env bash
# Run Sparkle's `generate_appcast` against a folder of update archives. The
# tool reads the EdDSA private key from the keychain (service
# "https://sparkle-project.org", account "ed25519"). Locally that's the key
# generated by `generate_keys`; in CI it's pre-seeded via
# `security add-generic-password` (see release.yml).
set -euo pipefail

RELEASES_DIR="${1:-./releases}"
VERSION=$(/usr/libexec/PlistBuddy -c "Print :CFBundleShortVersionString" BundleResources/Info.plist)

GEN=$(find .build/artifacts -type f -name generate_appcast -perm -u+x | head -1)
if [ -z "$GEN" ]; then
    echo "generate_appcast not found; run 'swift package resolve' first"
    exit 1
fi

if [ ! -d "$RELEASES_DIR" ]; then
    echo "Releases dir not found: $RELEASES_DIR"
    exit 1
fi

# --download-url-prefix points enclosure URLs at GitHub Release assets while
# the appcast itself lives on gh-pages. Trailing slash is required.
"$GEN" \
    --download-url-prefix "https://github.com/MartinRybergLaude/jetline/releases/download/v$VERSION/" \
    "$RELEASES_DIR"

cp "$RELEASES_DIR/appcast.xml" ./appcast.xml
echo "Appcast: ./appcast.xml"
